init:
  - git config --global core.autocrlf input

clone_depth: 1
test: off
os: Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
  - cmd: git fetch --depth 50
  - cmd: git fetch --tags --depth 50
  - cmd: git fetch origin master:master --depth 50
  - cmd: bash ./script/prepare-appveyor.sh
    # Display .NET Core info
  - cmd: dotnet --info
  # Restore build script
  - cmd: dotnet restore build
  # Install node
  - ps: Install-Product node ''

before_build:
  - cmd: bash ./script/git-version.sh --verbose get

build_script:
  - cmd: dotnet build build

artifacts:
  - path: bin/*.nupkg

deploy:
  - provider: Environment
    name: YoloDev MyGet
    on:
      branch: master

  - provider: Environment
    name: NuGet Central
    on:
      appveyor_repo_tag: true
